#!/bin/bash
clear
clear
echo -e "  ************************************************"
echo -e "     Halaman Login Xderm Mini Remover by cr4r "
echo -e "  ************************************************"
echo -e " "
echo -e "Notes : "
echo -e "- Script ini akan menghapus halaman login xderm-mini"
echo -e "- Hapus semua history dan cache setelah dihapus!"
echo -e "- Jika ada bug, buka incognito tab"
echo -e "- Jika masih terjadi bug, buka browser lain"
echo -e ""
echo -e " Proses akan dimulai dalam 3 secs....."
sleep 3
echo -e " Penghapusan dimulai..."
sleep 2
echo -e ""

echo -e " Mencari file login.php..."
nyari=$(find /www/xderm)
if [[ $nyari == *"login.php"* ]]; then
rm -rf /www/xderm/login.php
echo -e " file login.php berhasil dihapus !"
sleep 1
else
echo -e " Gagal dihapus ! Karena file login.php tidak ada"
sleep 1
fi

echo -e " Mencari file header.php..."
nyari=$(find /www/xderm)
if [[ $nyari == *"header.php"* ]]; then
rm -rf /www/xderm/header.php
echo -e " File header.php berhasil dihapus !"
sleep 1
else
echo -e " Gagal dihapus ! Karena file header.php tidak ditemukan"
sleep 1
fi

echo -e " Proses penghapusan selesai..."